services:
  usdatabase:
    image: mysql:9.0
    container_name: usDatabase
    restart: always
    ports:
      - "${MYSQL_PORT}:3306" # Map MySQL default port
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql", "-pmysql"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
volumes:
  mysql_data: # Declare a named volume for MySQL