services:
  app:
    build: .
    ports:
      - '4000:4000' # Map port 4000 of the container to port 4000 on the host
    env_file:
      - .env
    volumes:
      - .:/app # Mount the current directory to /app in the container
